### ISSUE TITLE
Stack frames are missing native methods on x86-32

### ISSUE THREAD

**Issue by penberg** [jatovm/jato#29]
StackTraceTest reports the following with OpenJDK (with Jato specific test cases commented out):

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: jvm/StackTraceTest.nativeMethod()V
   at jvm.StackTraceTest.nativeMethod(Native Method)
   at jvm.StackTraceTest.testJNIUnsatisfiedLinkErrorStackTrace(StackTraceTest.java:91)
   at jvm.StackTraceTest.main(StackTraceTest.java:111)
```

Jato on x86-64 reports the same thing:

```
 Exception in thread "main" java.lang.UnsatisfiedLinkError: jvm.StackTraceTest.nativeMethod()V
    at jvm.StackTraceTest.nativeMethod(Native Method)
    at jvm.StackTraceTest.testJNIUnsatisfiedLinkErrorStackTrace(StackTraceTest.java:91)
    at jvm.StackTraceTest.main(StackTraceTest.java:111)
```

but on x86-32 the native method is missing:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: jvm/StackTraceTest.nativeMethod()V
   at jvm.StackTraceTest.testJNIUnsatisfiedLinkErrorStackTrace(StackTraceTest.java:91)
   at jvm.StackTraceTest.main(StackTraceTest.java:111)
```

**Comment by penberg** [comment]
Fixed by commit 236c98248b01617e126a947bda48372aabe99a72.
