### ISSUE TITLE
sun/misc/Unsafe.arrayBaseOffset is missing

### ISSUE THREAD

**Issue by penberg** [jatovm/jato#6]
Jython 2.5.2rc4 fails to start up under Jato:

$ jato -jar jython.jar 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError:  
sun/misc/Unsafe.arrayBaseOffset(Ljava/lang/Class;)I
 at java.util.concurrent.atomic.AtomicReferenceArray.<clinit>(AtomicReferenceArray.java:24)
 at org.python.google.common.collect.CustomConcurrentHashMap$Segment.newEntryArray(CustomConcurrentHashMap.java:1683)
 at org.python.google.common.collect.CustomConcurrentHashMap$Segment.<init>(CustomConcurrentHashMap.java:1670)
 at org.python.google.common.collect.CustomConcurrentHashMap.<init>(CustomConcurrentHashMap.java:269)
 at org.python.google.common.collect.MapMaker.makeMap(MapMaker.java:440)
 at org.python.core.PyType.fromClass(PyType.java:1280)
 at org.python.core.PyObject.<init>(PyObject.java:66)
 at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:21)
 at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
 at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:24)
 at org.python.core.PyType$type___subclasses___exposer.<init>(Unknown Source)
 at org.python.core.PyType$PyExposer.<init>(Unknown Source)
 at org.python.core.PyType.<clinit>(PyType.java:33)
 at org.python.core.PyObject.<init>(PyObject.java:66)
 at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:21)
 at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
 at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:24)
 at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
 at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
 at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
 at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
 at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
 at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
 at org.python.core.PyObject.<clinit>(PyObject.java:26)
 at org.python.util.jython.run(jython.java:150)
 at org.python.util.jython.main(jython.java:129)
```

**Comment by penberg** [comment]
Fixed.
